### ISSUE TITLE
Flatpak version without environment option

### ISSUE THREAD

**Issue by AdsonCicilioti** [treagod/spectator#60] opened 2021-03-27 16:42 UTC
![Captura de tela de 2021-03-27 13-39-43](https://user-images.githubusercontent.com/6278398/112727600-fac6bd80-8f01-11eb-8d58-6ee835c765d7.png)

OS: Archlinux
Gnome: 3.38

**Comment by treagod** [comment] 2021-04-06 13:57
Sorry, I didn't release just yet. Will do it in the next view days. Thank you for reminding me

**Comment by treagod** [comment] 2021-05-02 07:05
I've updated the flatpack version. Please tell me if everything works allright

**Comment by AdsonCicilioti** [comment] 2021-05-04 17:38
Nice!! Environments working on Flatpak Version.
Now.. how a use Env vars on url requests?

**Comment by treagod** [comment] 2021-05-05 06:28
Happy that you're pleased.

Can you give some more information about the issue? Telling me each step? Just now I installed the Flatpak Spectator version and everything's working fine for me.

**Comment by treagod** [comment] 2021-05-22 17:07
Any updates to this? Otherwise I would close this issue because it's not reproducible

**Closed** 2021-07-15 12:37 UTC
